from app.cognitive.evidence import LearningEvidence


# Simulate evidence generated by the Coding Agent
evidence = LearningEvidence(
    user_id="student_001",
    concept_name="Recursion",
    source_agent="coding",
    evidence_type="coding_solution",
    performance=0.90,
    difficulty=0.80,
    reliability=0.80
)


print("----- CROSS-AGENT EVIDENCE -----")

print("Student:", evidence.user_id)
print("Concept:", evidence.concept_name)
print("Source Agent:", evidence.source_agent)
print("Evidence Type:", evidence.evidence_type)
print("Performance:", evidence.performance)
print("Difficulty:", evidence.difficulty)
print("Reliability:", evidence.reliability)
print("Timestamp:", evidence.timestamp)
