from app.cognitive.models import StudentCognitiveModel
from app.cognitive.evidence import LearningEvidence
from app.cognitive.evidence_store import EvidenceStore
from app.cognitive.mastery_engine import MasteryEngine
from app.cognitive.conflict_detector import ConflictDetector


class CognitiveEngine:
    """
    Central cognitive processing layer shared by all agents.

    Responsibilities:
    1. Store cross-agent evidence
    2. Update concept mastery
    3. Detect cognitive conflicts
    4. Maintain active conflict state
    5. Resolve conflicts using diagnostic evidence
    """

    def __init__(self):

        # Stores evidence produced by all agents
        self.evidence_store = EvidenceStore()

        # Updates concept mastery and confidence
        self.mastery_engine = MasteryEngine()

        # Detects disagreement between agents
        self.conflict_detector = ConflictDetector()

        # Stores unresolved conflicts.
        #
        # Format:
        # (user_id, concept_name) -> list of conflicts
        self.active_conflicts = {}


    # ==================================================
    # PROCESS NEW EVIDENCE
    # ==================================================

    def process_evidence(
        self,
        student: StudentCognitiveModel,
        evidence: LearningEvidence,
    ):
        """
        Process evidence generated by any agent.

        Flow:
        1. Validate student
        2. Get previous evidence
        3. Detect cross-agent conflicts
        4. Store evidence
        5. Update mastery
        6. Store new conflicts
        7. Check conflict resolution
        8. Return result
        """

        # --------------------------------------------------
        # STEP 1: Validate student
        # --------------------------------------------------

        if student.user_id != evidence.user_id:
            raise ValueError(
                "Evidence belongs to a different student."
            )


        # --------------------------------------------------
        # STEP 2: Get previous evidence for this concept
        # --------------------------------------------------

        previous_evidence = (
            self.evidence_store.get_evidence_for_concept(
                user_id=evidence.user_id,
                concept_name=evidence.concept_name,
            )
        )


        # --------------------------------------------------
        # STEP 3: Detect cross-agent conflicts
        # --------------------------------------------------

        new_conflicts = []

        for old_evidence in previous_evidence:

            # Conflict detection only makes sense
            # between different agents.
            if (
                old_evidence.source_agent
                == evidence.source_agent
            ):
                continue

            conflict = self.conflict_detector.detect(
                old_evidence,
                evidence,
            )

            if conflict is not None:
                new_conflicts.append(conflict)


        # --------------------------------------------------
        # STEP 4: Store the new evidence
        # --------------------------------------------------

        self.evidence_store.add_evidence(
            evidence
        )


        # --------------------------------------------------
        # STEP 5: Update student mastery
        # --------------------------------------------------

        updated_concept = (
            self.mastery_engine.update_from_evidence(
                student=student,
                evidence=evidence,
            )
        )


        # --------------------------------------------------
        # STEP 6: Store newly detected conflicts
        # --------------------------------------------------

        key = (
            evidence.user_id,
            evidence.concept_name.lower(),
        )

        if new_conflicts:

            self.active_conflicts.setdefault(
                key,
                []
            ).extend(
                new_conflicts
            )


        # --------------------------------------------------
        # STEP 7: Check whether diagnostic evidence
        #         can resolve the active conflict
        # --------------------------------------------------

        conflict_resolved = False

        if self.has_conflict(
            evidence.user_id,
            evidence.concept_name,
        ):

            if self.evaluate_conflict_resolution(
                evidence
            ):

                self.resolve_conflicts(
                    evidence.user_id,
                    evidence.concept_name,
                )

                conflict_resolved = True


        # --------------------------------------------------
        # STEP 8: Return complete processing result
        # --------------------------------------------------

        return {
            "concept": updated_concept,

            "conflicts": new_conflicts,

            "has_active_conflict": self.has_conflict(
                evidence.user_id,
                evidence.concept_name,
            ),

            "conflict_resolved": conflict_resolved,

            "evidence": evidence,
        }


    # ==================================================
    # CHECK ACTIVE CONFLICT
    # ==================================================

    def has_conflict(
        self,
        user_id: str,
        concept_name: str,
    ) -> bool:
        """
        Return True if the concept currently has
        an unresolved cognitive conflict.
        """

        key = (
            user_id,
            concept_name.lower(),
        )

        return bool(
            self.active_conflicts.get(key)
        )


    # ==================================================
    # GET ACTIVE CONFLICTS
    # ==================================================

    def get_conflicts(
        self,
        user_id: str,
        concept_name: str,
    ):
        """
        Return all active conflicts for a concept.
        """

        key = (
            user_id,
            concept_name.lower(),
        )

        return self.active_conflicts.get(
            key,
            []
        )


    # ==================================================
    # EVALUATE CONFLICT RESOLUTION
    # ==================================================

    def evaluate_conflict_resolution(
        self,
        evidence: LearningEvidence,
    ) -> bool:
        """
        Determine whether new evidence is strong enough
        to resolve an existing cognitive conflict.

        Initial experimental policy:

        1. Evidence must come from a diagnostic quiz.
        2. Reliability must be at least 0.70.
        3. Difficulty must be at least 0.50.

        These thresholds are prototype parameters and
        can later be tuned experimentally.
        """

        # Only diagnostic evidence can currently
        # resolve a conflict.
        if evidence.evidence_type != "diagnostic_quiz":
            return False

        # Reject evidence with low reliability.
        if evidence.reliability < 0.70:
            return False

        # Reject diagnostics that are too easy
        # to provide useful evidence.
        if evidence.difficulty < 0.50:
            return False

        return True


    # ==================================================
    # RESOLVE CONFLICT
    # ==================================================

    def resolve_conflicts(
        self,
        user_id: str,
        concept_name: str,
    ):
        """
        Remove active conflicts for a concept.

        This should only be called when sufficient
        diagnostic evidence has been obtained.
        """

        key = (
            user_id,
            concept_name.lower(),
        )

        self.active_conflicts.pop(
            key,
            None
        )