from dataclasses import dataclass

from app.cognitive.evidence import LearningEvidence


@dataclass
class CognitiveConflict:
    """
    Represents disagreement between evidence
    generated by two different agents.
    """

    concept_name: str

    first_agent: str
    second_agent: str

    first_performance: float
    second_performance: float

    difference: float

    severity: str


class ConflictDetector:
    """
    Detects when different agents provide substantially
    different evidence about the same concept.
    """

    def __init__(
        self,
        conflict_threshold: float = 0.35,
        high_conflict_threshold: float = 0.60,
    ):
        self.conflict_threshold = conflict_threshold
        self.high_conflict_threshold = high_conflict_threshold

    def detect(
        self,
        first_evidence: LearningEvidence,
        second_evidence: LearningEvidence,
    ):
        """
        Compare two evidence objects.

        Returns a CognitiveConflict if significant
        disagreement exists.

        Otherwise returns None.
        """

        # We only compare evidence about the same student.
        if first_evidence.user_id != second_evidence.user_id:
            return None

        # We only compare evidence about the same concept.
        if (
            first_evidence.concept_name.lower()
            != second_evidence.concept_name.lower()
        ):
            return None

        # Cross-agent conflict requires different agents.
        if first_evidence.source_agent == second_evidence.source_agent:
            return None

        # Calculate disagreement between performances.
        difference = abs(
            first_evidence.performance
            - second_evidence.performance
        )

        # Difference is too small to count as a conflict.
        if difference < self.conflict_threshold:
            return None

        # Determine severity.
        if difference >= self.high_conflict_threshold:
            severity = "high"
        else:
            severity = "moderate"

        return CognitiveConflict(
            concept_name=first_evidence.concept_name,
            first_agent=first_evidence.source_agent,
            second_agent=second_evidence.source_agent,
            first_performance=first_evidence.performance,
            second_performance=second_evidence.performance,
            difference=round(difference, 3),
            severity=severity,
        )