from app.cognitive.evidence import LearningEvidence


class EvidenceStore:
    """
    Stores cognitive evidence generated by all agents.

    This is currently an in-memory implementation.
    Later, we can replace or extend it with persistent
    database storage.
    """

    def __init__(self):
        # Stores all evidence objects.
        self.evidence_history: list[LearningEvidence] = []

    def add_evidence(self, evidence: LearningEvidence):
        """
        Add new evidence to the history.
        """

        self.evidence_history.append(evidence)

    def get_all_evidence(self):
        """
        Return all stored evidence.
        """

        return self.evidence_history.copy()

    def get_evidence_for_student(
        self,
        user_id: str
    ):
        """
        Return all evidence belonging to one student.
        """

        return [
            evidence
            for evidence in self.evidence_history
            if evidence.user_id == user_id
        ]

    def get_evidence_for_concept(
        self,
        user_id: str,
        concept_name: str
    ):
        """
        Return evidence for one particular concept
        belonging to one student.
        """

        return [
            evidence
            for evidence in self.evidence_history
            if (
                evidence.user_id == user_id
                and evidence.concept_name.lower()
                == concept_name.lower()
            )
        ]

    def get_evidence_from_agent(
        self,
        user_id: str,
        source_agent: str
    ):
        """
        Return evidence generated by a particular agent
        for one student.
        """

        return [
            evidence
            for evidence in self.evidence_history
            if (
                evidence.user_id == user_id
                and evidence.source_agent.lower()
                == source_agent.lower()
            )
        ]

    def get_latest_evidence(
        self,
        user_id: str,
        concept_name: str,
        source_agent: str | None = None
    ):
        """
        Return the most recent evidence for a concept.

        If source_agent is provided, return the most recent
        evidence from that specific agent.
        """

        matches = self.get_evidence_for_concept(
            user_id,
            concept_name
        )

        if source_agent is not None:
            matches = [
                evidence
                for evidence in matches
                if evidence.source_agent.lower()
                == source_agent.lower()
            ]

        if not matches:
            return None

        return max(
            matches,
            key=lambda evidence: evidence.timestamp
        )