from datetime import datetime

from app.cognitive.models import StudentCognitiveModel
from app.cognitive.evidence import LearningEvidence


class MasteryEngine:
    """
    Updates the student's cognitive state using evidence
    generated by Learning, Research, or Coding agents.
    """

    def update_from_evidence(
        self,
        student: StudentCognitiveModel,
        evidence: LearningEvidence,
    ):
        """
        Update concept mastery using one LearningEvidence object.
        """

        # Safety check:
        # Evidence must belong to the same student.
        if student.user_id != evidence.user_id:
            raise ValueError(
                "Evidence user_id does not match student user_id."
            )

        # Get current state of the concept.
        concept = student.get_concept(evidence.concept_name)

        old_mastery = concept.mastery

        # -------------------------------------------------
        # STEP 1: Calculate difficulty influence
        # -------------------------------------------------
        #
        # Harder activities can provide somewhat stronger
        # evidence than very easy activities.
        #
        # difficulty = 0 → factor = 0.5
        # difficulty = 1 → factor = 1.0

        difficulty_factor = 0.5 + (0.5 * evidence.difficulty)

        # -------------------------------------------------
        # STEP 2: Calculate effective evidence weight
        # -------------------------------------------------

        evidence_weight = (
            evidence.reliability * difficulty_factor
        )

        # -------------------------------------------------
        # STEP 3: Update mastery
        # -------------------------------------------------

        new_mastery = old_mastery + (
            evidence_weight
            * (evidence.performance - old_mastery)
        )

        # Keep mastery between 0 and 1.
        new_mastery = max(0.0, min(1.0, new_mastery))

        concept.mastery = round(new_mastery, 3)

        # -------------------------------------------------
        # STEP 4: Update interaction count
        # -------------------------------------------------

        concept.attempts += 1

        # -------------------------------------------------
        # STEP 5: Update confidence
        # -------------------------------------------------

        concept.confidence = min(
            1.0,
            concept.confidence + (0.1 * evidence_weight)
        )

        concept.confidence = round(
            concept.confidence,
            3
        )

        concept.last_updated = datetime.now()

        return concept